name: static-analysis

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Ruff
      run: pip install ruff
    - name: Check format with ruff
      run: ruff format --check --verbose .

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Set up flake8 annotations
      uses: rbialon/flake8-annotations@v1
    - name: Install Ruff
      run: pip install ruff
    - name: Lint with ruff
      run: ruff check --verbose .

  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Audit dependencies
      run: |
        make -B audit